
print('\033[1;36m wwwww    wwww    wwwww  DDDDDDDDDD  OOOOOOOOOO\           HHH      HHH        A        KK   KK   CCCCCCCCCCCCCCC  IIIIIIIIIII   NNNN     NN  GGGGGGGGGGGGGG')
print('  wwwww  wwwwww  wwwww   DDD         OOO      OO           HHH      HHH       AAA       KK  KK    CCCC                IIIII      NN NN    NN  GGGGGGGGGGGGGGGGG')
print('   wwwwwwww  wwwwwwww    DDD         OO       OO           HHH      HHH      AA AA      KK KK     CCC                  III       NN  NN   NN  GGG              ')
print('    wwwwww    wwwwww     DDDDDDDDDD  OOOOOOOOOO            HHHHHHHHHHHH     AA   AA     KKKK      CC                   III       NN   NN  NN  GGG     GGGGGGGG\ ')
print('     wwww      wwww      DDD         OO       OO           HHH      HHH    AAAAAAAAA    KK KK     CCC                  III       NN    NN NN  GGG            GG')
print('      ww        ww       DDD         OOO      OO           HHH      HHH   AA       AA   KK  KK    CCCC                IIIII      NN     NNNN  GGGGGGGGGGGGGGGGG')
print('       w        w        DDDDDDDDDD  OOOOOOOOOO/           HHH      HHH  AA         AA  KK   KK   CCCCCCCCCCCCCCC  IIIIIIIIIII   NN      NNN  GGGGGGGGGGGGGGGGG\n')

print('\033[1;32m                                                     WEBSITE HACKING                                                                                                                                                                                        \033[0m')
print('\033[1;36m                                                         BY THEJ                                                                                                                                                                                          \033[0m\n')
print('\033[1;32m                                             PLEASE INSERT CORRECT INFORMATIONS          \033[0m\n')
print('\033[1;36m')
name = input('Type your name hear: \n')
print('\n')
print('\033[1;32m    To insert the number please type 0 instead of +94               \033[0m')
print('\033[1;36m')
number = input('Type your whatsapp number hear please: \n')

html = input('paste the link of website what should be hack: \n')
print('LOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\n')
print('\033[1;34mLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\033[0m\n')
print('\033[1;32mLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\n')
print('\033[1;33mLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\n')
print('\033[1;31mLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\nLOADING.........................\n')
print('\n')
print('\033[1;33m ඕයි ' + name + ' උබ හිතුවද ලේසියෙන් web එකක් hack කරන්න? එහෙනම් යට බලපන්')
print('මුලින්ම python ඉගෙන ගනින් මොකද ඒක ලේසියි ඊට පස්සෙ මම මේ යටින් දාන number එකට whatsapp msg එකක් දාන්න\n')
print('\033[1;33m ඕයි ' + name + ' උබ හිතුවද ලේසියෙන් web එකක් hack කරන්න? එහෙනම් යට බලපන්')
print('මුලින්ම python ඉගෙන ගනින් මොකද ඒක ලේසියි ඊට පස්සෙ මම මේ යටින් දාන number එකට whatsapp msg එකක් දාන්න\n')
print('\033[1;33m ඕයි ' + name + ' උබ හිතුවද ලේසියෙන් web එකක් hack කරන්න? එහෙනම් යට බලපන්')
print('මුලින්ම python ඉගෙන ගනින් මොකද ඒක ලේසියි ඊට පස්සෙ මම මේ යටින් දාන number එකට whatsapp msg එකක් දාන්න\n')
print('\033[1;33m ඕයි ' + name + ' උබ හිතුවද ලේසියෙන් web එකක් hack කරන්න? එහෙනම් යට බලපන්')
print('මුලින්ම python ඉගෙන ගනින් මොකද ඒක ලේසියි ඊට පස්සෙ මම මේ යටින් දාන number එකට whatsapp msg එකක් දාන්න\n')
print('\033[1;33m                            0753123605                \033[0m')
print('\033[1;34m                      ඕනෙ නම් බැනපන්😂😂\033[0m')

